version: '3.3'

services:

  postgres-template:
    image: "postgres:10"

  template-server:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-template
    ports:
      - "8080:8080"